core:
  grav:
    version: 1.7.48
    history:
      version: 1.6.30
      date: '2020-12-14 16:06:47'
      0: { version: 1.7.5, date: '2021-02-03 17:46:50' }
      1: { version: 1.7.7, date: '2021-03-10 10:00:29' }
      2: { version: 1.7.9, date: '2021-04-05 08:33:03' }
      3: { version: 1.7.12, date: '2021-04-19 09:25:04' }
      4: { version: 1.7.13, date: '2021-04-27 10:30:32' }
      5: { version: 1.7.14, date: '2021-05-10 10:52:05' }
      6: { version: 1.7.16, date: '2021-06-14 09:32:07' }
      7: { version: 1.7.17, date: '2021-06-30 08:50:43' }
      8: { version: 1.7.18, date: '2021-07-23 10:31:45' }
      9: { version: 1.7.22, date: '2021-09-20 09:13:39' }
      10: { version: 1.7.23, date: '2021-10-01 06:50:16' }
      11: { version: 1.7.24, date: '2021-11-09 10:03:49' }
      12: { version: 1.7.25, date: '2021-11-18 20:04:35' }
      13: { version: 1.7.30, date: '2022-03-01 10:51:20' }
      14: { version: 1.7.33, date: '2022-05-16 13:10:21' }
      15: { version: 1.7.34, date: '2022-06-22 08:44:17' }
      16: { version: 1.7.35, date: '2022-08-31 09:00:01' }
      17: { version: 1.7.36, date: '2022-09-26 10:04:13' }
      18: { version: 1.7.37.1, date: '2022-10-12 10:03:04' }
      19: { version: 1.7.40, date: '2023-04-03 10:56:44' }
      20: { version: 1.7.42.3, date: '2023-07-28 08:45:40' }
      21: { version: 1.7.43, date: '2023-10-17 09:25:49' }
      22: { version: 1.7.44, date: '2024-02-12 08:29:18' }
      23: { version: 1.7.45, date: '2024-03-23 08:34:25' }
      24: { version: 1.7.46, date: '2024-07-18 10:38:20' }
      25: { version: 1.7.48, date: '2025-03-11 10:53:31' }
    schema: 1.7.0_2020-11-20_1
